services:

  T3docs\RestructuredApiTools\Command\PhpDomainCommand:
    tags:
      - name: 'console.command'
        command: 'restructured_api_tools:php_domain'
        description: 'An example description for a command'
        # not required, defaults to false
        hidden: false
