services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  T3docs\Codesnippet\:
    resource: '../Classes/*'

  T3docs\Codesnippet\Command\PhpDomainCommand:
    tags:
      - name: 'console.command'
        command: 'codesnippet:create'
        description: 'Create codesnippets'
        # not required, defaults to false
        hidden: false
