services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  T3docs\Codesnippet\:
    resource: '../Classes/*'

  T3docs\Codesnippet\Command\PhpDomainCommand:
    public: true
    tags:
      - name: 'console.command'
        command: 'codesnippet:create'
        description: 'Create codesnippets'

  T3docs\Codesnippet\Command\BaselineCommand:
    public: true
    tags:
      - name: 'console.command'
        command: 'codesnippet:baseline'
        description: 'Create baseline for functional tests'

  T3docs\Codesnippet\Util\CodeSnippetCreator:
    public: true

  T3docs\Codesnippet\Renderer\PhpDomainRenderer:
    public: true


  T3docs\Codesnippet\Twig\AppExtension:
    tags: ['twig.extension']
