services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  T3docs\Codesnippet\:
    resource: '../Classes/*'

  T3docs\Codesnippet\Command\PhpDomainCommand:
    public: true
    tags:
      - name: 'console.command'
        command: 'codesnippet:create'
        description: 'Create codesnippets'

  T3docs\Codesnippet\Command\BaselineCommand:
    public: true
    tags:
      - name: 'console.command'
        command: 'codesnippet:baseline'
        description: 'Create baseline for functional tests'

  T3docs\Codesnippet\Renderer\CodeSnippetRenderer:
    tags:
      - name: 'codesnippet.renderer'

  T3docs\Codesnippet\Renderer\JsonCodeSnippetRenderer:
    tags:
      - name: 'codesnippet.renderer'

  T3docs\Codesnippet\Renderer\PhpArrayCodeSnippetRenderer:
    tags:
      - name: 'codesnippet.renderer'

  T3docs\Codesnippet\Renderer\PhpClassCodeSnippetRenderer:
    tags:
      - name: 'codesnippet.renderer'

  T3docs\Codesnippet\Renderer\PhpDomainRenderer:
    tags:
      - name: 'codesnippet.renderer'

#  T3docs\Codesnippet\Renderer\XmlCodeSnippetRenderer:
#    tags:
#      - name: 'codesnippet.renderer'

#  T3docs\Codesnippet\Renderer\YamlCodeSnippetRenderer:
#    tags:
#      - name: 'codesnippet.renderer'

  T3docs\Codesnippet\Twig\AppExtension:
    tags: ['twig.extension']

  T3docs\Codesnippet\Util\CodeSnippetCreator:
    arguments: [ !tagged_iterator { tag: 'codesnippet.renderer' } ]
