name: code-quality

on:
  push:
  pull_request:
  schedule:
    - cron:  '56 4 * * *'

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - '8.1'
          - '8.2'
          - '8.3'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint PHP
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s lint

  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Testing with PHP 7.4 and PHP8.0 is not done by intention. The codesnippet package needs to
          # handle PHP code and features only available in PHP8.1, thus this is the minimum version we
          # can test.
          - php: '8.1'
            core: '12.4'
          - php: '8.2'
            core: '12.4'
          - php: '8.3'
            core: '12.4'
          - php: '8.2'
            core: '13.0'
          - php: '8.3'
            core: '13.0'
          - php: '8.2'
            core: '13.1'
          - php: '8.3'
            core: '13.1'
          - php: '8.2'
            core: 'main'
          - php: '8.3'
            core: 'main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install testing system
        run: Build/Scripts/runTests.sh -t ${{ matrix.core }} -p ${{ matrix.php }} -s composerUpdate

      - name: Composer validate
        run: Build/Scripts/runTests.sh -t ${{ matrix.core }} -p ${{ matrix.php }} -s composerValidate

      - name: Composer normalize
        run: Build/Scripts/runTests.sh -t ${{ matrix.core }} -p ${{ matrix.php }} -s composerNormalize -n

      - name: CGL
        run: Build/Scripts/runTests.sh -t ${{ matrix.core }} -p ${{ matrix.php }} -s cgl -n

      - name: phpstan
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s phpstan

  xliff-lint:
    name: "XLIFF linter"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "XLIFF lint"
        uses: TYPO3-Continuous-Integration/TYPO3-CI-Xliff-Lint@v1
