name: code-quality

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron:  '56 4 * * *'

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Lint PHP
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s lint

  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php: '8.1'
            core: '12.4'
          - php: '8.2'
            core: '12.4'
          - php: '8.3'
            core: '12.4'
          - php: '8.4'
            core: '12.4'
          - php: '8.2'
            core: '13.4'
          - php: '8.3'
            core: '13.4'
          - php: '8.4'
            core: '13.4'
          - php: '8.5'
            core: '13.4'
          - php: '8.2'
            core: 'main'
          - php: '8.3'
            core: 'main'
          - php: '8.4'
            core: 'main'
          - php: '8.5'
            core: 'main'
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install testing system
        run: Build/Scripts/runTests.sh -t ${{ matrix.core }} -p ${{ matrix.php }} -s composerUpdate

      - name: Composer validate
        run: Build/Scripts/runTests.sh -t ${{ matrix.core }} -p ${{ matrix.php }} -s composerValidate

      - name: Composer normalize
        run: Build/Scripts/runTests.sh -t ${{ matrix.core }} -p ${{ matrix.php }} -s composerNormalize -n

      - name: CGL
        run: Build/Scripts/runTests.sh -t ${{ matrix.core }} -p ${{ matrix.php }} -s cgl -n

      - name: phpstan
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s phpstan
