name: tests 13.1

on:
  push:
  pull_request:
  schedule:
    - cron:  '56 4 * * *'

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - '8.2'
          - '8.3'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install testing system
        run: Build/Scripts/runTests.sh -t 13.1 -p ${{ matrix.php }} -s composerUpdate

      - name: Unit Tests
        run: Build/Scripts/runTests.sh -t 13.1 -p ${{ matrix.php }} -s unit

      - name: Unit Tests
        run: Build/Scripts/runTests.sh -t 13.1 -p ${{ matrix.php }} -s functional
