name: tests 13.4

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron:  '56 4 * * *'

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install testing system
        run: Build/Scripts/runTests.sh -t 13.4 -p ${{ matrix.php }} -s composerUpdate

      - name: Unit Tests
        run: Build/Scripts/runTests.sh -t 13.4 -p ${{ matrix.php }} -s unit

      - name: Functional Tests
        run: Build/Scripts/runTests.sh -t 13.4 -p ${{ matrix.php }} -s functional
