name: tests main

on:
  push:
  pull_request:
  schedule:
    - cron:  '56 4 * * *'
    
jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php:
          - '8.1'
          - '8.2'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install testing system
        run: Build/Scripts/runTests.sh -t main -p ${{ matrix.php }} -s composerUpdate

      - name: Unit Tests
        run: Build/Scripts/runTests.sh -t main -p ${{ matrix.php }} -s unit